/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectTopics_GUIBUILDER.apps;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class JListDemo extends javax.swing.JFrame {
    private String[] colors;
    private DefaultListModel dlm;
    private Map<String,Color> colorMap=new HashMap<>();;
    public JListDemo() {
        super("Prashant`s Frame");
        initComponents();
        super.setLocationRelativeTo(null);
        colors=new String[]{"Red","Green","Blue","Pink","White","Black"};
        dlm=new DefaultListModel();
       jlColor.setModel(dlm);
       
       colorMap.put("Red", Color.red);
       colorMap.put("Green", Color.green);
       colorMap.put("Blue", Color.blue);
       colorMap.put("Pink", Color.pink);
       colorMap.put("White", Color.white);
       colorMap.put("Black", Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlColor = new javax.swing.JList<>();
        btnAddColor = new javax.swing.JButton();
        btnDeleteColor = new javax.swing.JButton();
        btnShowSelected = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        btnApplyColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlColor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(jlColor);

        btnAddColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddColor.setText("AddColor");
        btnAddColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColorActionPerformed(evt);
            }
        });

        btnDeleteColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteColor.setText("DeleteColor");
        btnDeleteColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteColorActionPerformed(evt);
            }
        });

        btnShowSelected.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnShowSelected.setText("ShowSelected");
        btnShowSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSelectedActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnApplyColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnApplyColor.setText("ApplyColor");
        btnApplyColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddColor)
                .addGap(49, 49, 49)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(myPanelLayout.createSequentialGroup()
                                .addComponent(btnShowSelected)
                                .addGap(36, 36, 36)
                                .addComponent(btnDeleteColor)
                                .addGap(0, 16, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addComponent(btnApplyColor)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddColor)
                    .addComponent(btnShowSelected)
                    .addComponent(btnDeleteColor)
                    .addComponent(btnApplyColor))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColorActionPerformed
      for(String color:colors){
      dlm.addElement(color);
      }
    }//GEN-LAST:event_btnAddColorActionPerformed

    private void btnShowSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSelectedActionPerformed
      try {
        String colorName=jlColor.getSelectedValue();
        if(colorName==null){     
          throw new NoColorSelectedException("Plese select a color first");
         } 
        lblResult.setText("You selected: "+colorName);
        }catch(NoColorSelectedException ex){
        JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnShowSelectedActionPerformed

    private void btnDeleteColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteColorActionPerformed
        try{
        int index=jlColor.getSelectedIndex();
        if(index==-1){
        throw new NoColorSelectedException("Plese select a color first");
        }
         dlm.removeElementAt(index);
         lblResult.setText("Item Removed");
       }catch(NoColorSelectedException ex){
        JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnDeleteColorActionPerformed

    private void btnApplyColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyColorActionPerformed
        String colorName=jlColor.getSelectedValue();
//        if(colorName.equalsIgnoreCase("red")){
//        myPanel.setBackground(Color.red);
//        }else if(colorName.equalsIgnoreCase("black")){    ---->Budho wala trika
//        myPanel.setBackground(Color.black);
//        }

    myPanel.setBackground(colorMap.get(jlColor.getSelectedValue()));
    }//GEN-LAST:event_btnApplyColorActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JListDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddColor;
    private javax.swing.JButton btnApplyColor;
    private javax.swing.JButton btnDeleteColor;
    private javax.swing.JButton btnShowSelected;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlColor;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables
}
